name: autocomplete_textfield
description: An autocomplete textfield for flutter
version: 0.0.1
author: Felix McCuaig <felixmccuaigdev@gmail.com>
homepage: https://github.com/felixlucien/flutter-autocomplete-textfield

environment:
    sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter